# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  demos:
    cmds:
      # TODO: See if I can loop over *.tape in a dir instead of... this
      - vhs "./assets/bench.tape"
      - vhs "./assets/demo.tape"
      - vhs "./assets/fails.tape"
      - vhs "./assets/simple.tape"
      - vhs "./assets/verbose.tape"
    silent: true
