Output "./assets/config.gif"

Set Width 1000
Set Height 1200
Set FontFamily "MartianMono NFM"
Set FontSize 14

Hide
Type "go install ." Enter
Type "clear" Enter
Show

Type "prism config clear" Enter
Sleep 1

Type "prism config show" Enter
Sleep 2

Type "prism config set verbose true" Enter
Sleep 1

Type "prism config set only_fails true" Enter
Sleep 1

Type "prism config set show_color false" Enter
Sleep 1

Type "prism config show" Enter
Sleep 3

Type "prism" Enter
Sleep 5
